# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
