# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
