# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20160124_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
