# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20160128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
